# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
            bash Miniconda3-latest-Linux-x86_64.sh -b -p ~/miniconda
            source ~/miniconda/bin/activate
            conda env update -n base -f requirements.txt
            conda upgrade sip
            sudo apt-get install -y libfftw3-dev
            conda install -y -c conda-forge liblapack

      - run:
          name: run build steps
          command: |
            source ~/miniconda/bin/activate
            python setup.py build_ext --inplace
            python setup.py install --user

      - run:
          name: import pyrat and run basic commands
          command: |
            source ~/miniconda/bin/activate
            python -c "from pyrat import *"