#!/bin/sh
## sarshow: CLI to display a SAR data with an RGB rendering
##
## This file is part of NL-SAR Toolbox version 0.6.
##
## Copyright Charles-Alban Deledalle (2013)
## Email charles-alban.deledalle@math.u-bordeaux1.fr
##
## This software is a computer program whose purpose is to provide a
## suite of tools to manipulate SAR images.
##
## This software is governed by the CeCILL license under French law and
## abiding by the rules of distribution of free software. You can use,
## modify and/ or redistribute the software under the terms of the CeCILL
## license as circulated by CEA, CNRS and INRIA at the following URL
## "http://www.cecill.info".
##
## As a counterpart to the access to the source code and rights to copy,
## modify and redistribute granted by the license, users are provided only
## with a limited warranty and the software's author, the holder of the
## economic rights, and the successive licensors have only limited
## liability.
##
## In this respect, the user's attention is drawn to the risks associated
## with loading, using, modifying and/or developing or reproducing the
## software by the user in light of its specific status of free software,
## that may mean that it is complicated to manipulate, and that also
## therefore means that it is reserved for developers and experienced
## professionals having in-depth computer knowledge. Users are therefore
## encouraged to load and test the software's suitability as regards their
## requirements in conditions enabling the security of their systems and/or
## data to be ensured and, more generally, to use and operate it in the
## same conditions as regards security.
##
## The fact that you are presently reading this means that you have had
## knowledge of the CeCILL license and that you accept its terms.
##
##
## Started on  Wed Jul 24 14:52:50 2013 Charles-Alban Deledalle
## Last update Wed Jul 24 14:52:54 2013 Charles-Alban Deledalle
##

if [ $# -lt 1 ] ; then
   echo "Usage:" `basename $0` "filein [alpha = 3 gamma = 0.7]"
   exit 1
fi

mktempu()
{
    template=$1
    prefix=`echo $template | sed 's/\([^X]*X*\).*/\1/'`
    suffix=`echo $template | sed 's/[^X]*X*\(.*\)/\1/'`
    out_prefix=`mktemp -t $prefix`
    res=$?
    if [ $res -eq 0 ] ; then
	if [ "${out_prefix}" != "${out_prefix}${suffix}" ] ; then
            mv -f ${out_prefix} ${out_prefix}${suffix}
	fi
	out=${out_prefix}${suffix}
	echo $out
	rm -f $out
    fi
    return $res
}

filein=$1
bn=`mktempu $(basename filein)XXX.png`
log=`mktempu logXXX.txt`
`dirname $0`/sar2png $filein $bn $2 $3 2> $log
case $? in
    0)
	;;
    1)
	usage
	;;
    *)
	cat $log 1>&2
	rm -f $log
	exit 2
	;;
esac
rm -f $log
if [ "$NLSAR_VIEWER" = "" ] ; then
    echo "Please set your environment variable NLSAR_VIEWER"
    exit 2
fi
$NLSAR_VIEWER $bn 2>/dev/null 1>/dev/null
rm -f $bn
